name: Build and Deploy to Azure WebApp

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'Bibliotecadigital'
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Maven
      run: |
        mvn clean package -DskipTests

    - name: Run tests
      run: |
        mvn test

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.POM_XML_DIRECTORY }}/target/*.jar'
